version: '3.3'
services:
  db: 
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5434:5432" # External port is changed to prevent duplication with local Psql installation PORT
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local